language: erlang
otp_release:
  - 17.1
services:
  - redis-server
  - rabbitmq

addons:
  postgresql: "9.3"
before_install:
  - ./scripts/setup_travis
before_script:
  - "export PATH=`pwd`/tmp/elixir/bin:$PATH"
  - "export MIX_ENV=travis"
  - psql -c 'create database re_inspector_ci_test;' -U postgres
script:
  - mix deps.get
  - cd apps/re_inspector_app
  - mix do deps.get deps.compile, compile, ecto.migrate ReInspector.Repo
  - cd ../re_inspector_backend
  - mix do deps.get, deps.compile cowboy
  - cd ../..
  - mix test
