#!/bin/sh -e

APP_DIR="`pwd`/tmp"
mkdir -p $APP_DIR

export PATH=${APP_DIR}/elixir/bin:$PATH

if ! [ `which mix` ] ; then
  mkdir -p ${APP_DIR}/elixir
  curl -L https://github.com/elixir-lang/elixir/releases/download/v0.14.3/Precompiled.zip > ${APP_DIR}/elixir.zip
  unzip -u ${APP_DIR}/elixir.zip -d ${APP_DIR}/elixir
fi

mix local.hex --force
mix local.rebar --force

iex --version