#!/bin/sh -e

APP_DIR="`pwd`/tmp"
mkdir -p $APP_DIR

export PATH=${APP_DIR}/elixir/bin:$PATH

mkdir -p ${APP_DIR}/elixir
curl -L https://github.com/elixir-lang/elixir/releases/download/v1.0.1/Precompiled.zip > ${APP_DIR}/elixir.zip
unzip -u ${APP_DIR}/elixir.zip -d ${APP_DIR}/elixir

mix local.hex --force
mix local.rebar --force

cd apps/re_inspector_backend
npm install
npm install -g bower
bower install
cd -

iex --version